'use client';

import type { DenyCase, Decision, ObservedTransaction } from '@limen/core';
import { Verdict } from './Verdict';

export interface AdjudicatedCase {
  denyCase: DenyCase;
  decision: Decision;
}

/**
 * The product.
 *
 * Every row is a single-axis mutation of the observed transaction, adjudicated
 * by the same `evaluate` the test suite runs. The observed flow sits at the top
 * as the one PERMIT, so the contrast is visible without scrolling.
 */
export function DenyTable({
  observed,
  observedDecision,
  cases,
}: {
  observed: ObservedTransaction;
  observedDecision: Decision;
  cases: AdjudicatedCase[];
}) {
  const overPermissive = cases.filter(({ decision }) => decision.permitted);

  return (
    <div className="flex flex-col gap-3">
      {overPermissive.length > 0 && (
        <div
          role="alert"
          className="rounded-sm border border-deny bg-deny-dim px-3 py-2 text-deny"
        >
          <strong>Over-permissive.</strong> {overPermissive.length} adjacent transaction
          {overPermissive.length === 1 ? '' : 's'} that this policy must refuse
          {overPermissive.length === 1 ? ' was' : ' were'} permitted:{' '}
          {overPermissive.map(({ denyCase }) => denyCase.axis).join(', ')}.
        </div>
      )}

      <div className="scroll-x rounded-sm border border-border-subtle">
        <table className="w-full min-w-[52rem] border-collapse text-left">
          <thead>
            <tr className="border-b border-border-bright bg-surface-raised text-muted">
              <th scope="col" className="w-[7rem] px-3 py-2 font-medium tracking-wide uppercase">
                Verdict
              </th>
              <th scope="col" className="w-[6.5rem] px-3 py-2 font-medium tracking-wide uppercase">
                Axis
              </th>
              <th scope="col" className="px-3 py-2 font-medium tracking-wide uppercase">
                Transaction
              </th>
              <th scope="col" className="px-3 py-2 font-medium tracking-wide uppercase">
                Reason
              </th>
            </tr>
          </thead>
          <tbody>
            <tr className="border-b border-border-bright bg-permit-dim/30">
              <td className="px-3 py-3 align-top">
                <Verdict permitted={observedDecision.permitted} />
              </td>
              <td className="px-3 py-3 align-top text-muted-dim">observed</td>
              <td className="px-3 py-3 align-top">
                <div className="text-foreground">the transaction the policy was derived from</div>
                <div className="text-muted-dim">
                  {observed.invocations.length} invocation
                  {observed.invocations.length === 1 ? '' : 's'} at ledger {observed.ledger}
                </div>
              </td>
              <td className="px-3 py-3 align-top text-muted">
                {observedDecision.permitted
                  ? 'within every derived constraint'
                  : observedDecision.reasons.join('; ')}
              </td>
            </tr>

            {cases.map(({ denyCase, decision }) => {
              const wrong = decision.permitted;
              return (
                <tr
                  key={denyCase.axis}
                  className={`border-b border-border-subtle last:border-b-0 ${
                    wrong ? 'bg-deny-dim/40' : ''
                  }`}
                >
                  <td className="px-3 py-3 align-top">
                    <Verdict permitted={decision.permitted} />
                  </td>
                  <td className="px-3 py-3 align-top text-muted-dim">{denyCase.axis}</td>
                  <td className="px-3 py-3 align-top">
                    <div className="text-foreground">{denyCase.label}</div>
                    <div className="text-muted-dim">{denyCase.why}</div>
                  </td>
                  <td className="px-3 py-3 align-top text-muted">
                    {decision.reasons.length > 0 ? (
                      <ul className="flex flex-col gap-1">
                        {decision.reasons.map((reason) => (
                          <li key={reason}>{reason}</li>
                        ))}
                      </ul>
                    ) : (
                      <span className="text-deny">
                        no objection raised — this dimension of the policy is too wide
                      </span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      <p className="text-muted-dim">
        Each row changes exactly one dimension of the observed transaction, so a PERMIT here names
        the single over-permissive dimension. Rows are generated by{' '}
        <code className="text-muted">generateDenyCases</code> and adjudicated by{' '}
        <code className="text-muted">evaluate</code> — the same functions the test suite runs.
      </p>
    </div>
  );
}
